"""Closed JavaScript compatibility runtime helpers for generated Python."""

from tsonic_python_js.arrays import JsArray
from tsonic_python_js.collections import JsMap, JsSet
from tsonic_python_js.dates import JsDate
from tsonic_python_js.dynamic import JsValue
from tsonic_python_js.equality import object_is, same_value_zero, strict_equal
from tsonic_python_js.errors import (
    JsError,
    JsRangeError,
    JsReferenceError,
    JsSyntaxError,
    JsTypeError,
    JsUnsupportedError,
    JsURIError,
)
from tsonic_python_js.json import json_parse, json_stringify
from tsonic_python_js.numbers import (
    is_finite,
    is_integer,
    is_nan,
    is_safe_integer,
    math_abs,
    math_ceil,
    math_clz32,
    math_floor,
    math_imul,
    math_max,
    math_min,
    math_pow,
    math_round,
    math_sign,
    math_sqrt,
    math_trunc,
    parse_float,
    parse_int,
    to_int32,
    to_number,
    to_uint32,
)
from tsonic_python_js.objects import (
    JsObject,
    delete_property,
    get_property,
    property_key,
    set_property,
)
from tsonic_python_js.regexp import REGEXP_STATUS, unsupported_regexp
from tsonic_python_js.strings import (
    char_at,
    char_code_at,
    ends_with,
    from_char_code,
    from_code_point,
    includes,
    index_of,
    js_slice_indices,
    last_index_of,
    pad_end,
    pad_start,
    repeat,
    split,
    starts_with,
    string_slice,
    substr,
    substring,
    trim,
    trim_end,
    trim_start,
    utf16_code_units,
    utf16_len,
)
from tsonic_python_js.typed_arrays import (
    ArrayBuffer,
    DataView,
    Float32Array,
    Float64Array,
    Int8Array,
    Int16Array,
    Int32Array,
    TypedArray,
    Uint8Array,
    Uint8ClampedArray,
    Uint16Array,
    Uint32Array,
)
from tsonic_python_js.values import is_nullish, is_undefined, undefined

__all__ = [
    "REGEXP_STATUS",
    "ArrayBuffer",
    "DataView",
    "Float32Array",
    "Float64Array",
    "Int8Array",
    "Int16Array",
    "Int32Array",
    "JsArray",
    "JsDate",
    "JsError",
    "JsMap",
    "JsObject",
    "JsRangeError",
    "JsReferenceError",
    "JsSet",
    "JsSyntaxError",
    "JsTypeError",
    "JsURIError",
    "JsUnsupportedError",
    "JsValue",
    "TypedArray",
    "Uint8Array",
    "Uint8ClampedArray",
    "Uint16Array",
    "Uint32Array",
    "char_at",
    "char_code_at",
    "delete_property",
    "ends_with",
    "from_char_code",
    "from_code_point",
    "get_property",
    "includes",
    "index_of",
    "is_finite",
    "is_integer",
    "is_nan",
    "is_nullish",
    "is_safe_integer",
    "is_undefined",
    "js_slice_indices",
    "json_parse",
    "json_stringify",
    "last_index_of",
    "math_abs",
    "math_ceil",
    "math_clz32",
    "math_floor",
    "math_imul",
    "math_max",
    "math_min",
    "math_pow",
    "math_round",
    "math_sign",
    "math_sqrt",
    "math_trunc",
    "object_is",
    "pad_end",
    "pad_start",
    "parse_float",
    "parse_int",
    "property_key",
    "repeat",
    "same_value_zero",
    "set_property",
    "split",
    "starts_with",
    "strict_equal",
    "string_slice",
    "substr",
    "substring",
    "to_int32",
    "to_number",
    "to_uint32",
    "trim",
    "trim_end",
    "trim_start",
    "undefined",
    "unsupported_regexp",
    "utf16_code_units",
    "utf16_len",
]
